templates-directory: "tools/nuclei-templates"
tags:
  - takeovers
  - file-upload
  - rce
  - cve
exclude-tags:
  - code
severity:
  - critical
  - high
rate-limit: 200
bulk-size: 25
retries: 1
timeout: 10
metrics: true
project: true